### ISSUE TITLE
Login returns 404

### ISSUE THREAD

**Issue by dunklesToast** [victorkane/nuxt-auth-routes-on-express#2]
Just cloned the repo and tried to login. Got a 404 error after pressing the Login Button.
The software tried to reach `/undefined/api/login`

**Comment by georgebutter** [comment]
@dunklesToast You need to set an environment variable.

https://github.com/victorkane/nuxt-auth-routes-on-express/blob/241156b33192794e784cff95f5960ad1907e1124/store/index.js#L30
